version: '3'

services:
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=p@ssw0rd
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: dvwa-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
